config/routes.rb
Rails.application.routes.draw do
  root "gardens#index"
  resources :gardens do
    resources :plants, only: [:create]
  end
  resources :plants, only: [:destroy] do
    resources :plant_tags, only: [:new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :banner_url, presence: true
  has_many :plants, dependent: :destroy # gives access to plants that belong to given garden with garden.plants
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden # Creates a validation && gives the access to the garden with plant.garden
  has_many :plant_tags, dependent: :destroy # plant.plant_tags
  has_many :tags, through: :plant_tags # plant.tags
end

app/models/plant_tag.rb
class PlantTag < ApplicationRecord
  belongs_to :plant # 1/ Validation 2/ Gives plant_tag.plant
  belongs_to :tag  # 1/ Validation 2/ Gives plant_tag.garden
  validates :plant, uniqueness: { scope: :tag }
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :plant_tags, dependent: :destroy
  has_many :plants, through: :plant_tags
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: [:show, :edit, :update, :destroy]

  # GET /gardens
  def index
    @gardens = Garden.all
  end

  # GET /gardens/1
  def show
    @garden = Garden.find(params[:id])
    @plant = Plant.new
  end

  # GET /gardens/new
  def new
    @garden = Garden.new
  end

  # GET /gardens/1/edit
  def edit
  end

  # POST /gardens
  def create
    @garden = Garden.new(garden_params)

    if @garden.save
      redirect_to @garden, notice: 'Garden was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /gardens/1
  def update
    if @garden.update(garden_params)
      redirect_to @garden, notice: 'Garden was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /gardens/1
  def destroy
    @garden.destroy
    redirect_to gardens_url, notice: 'Garden was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_garden
      @garden = Garden.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def garden_params
      params.require(:garden).permit(:name, :banner_url)
    end
end

app/controllers/plant_tags_controller.rb
class PlantTagsController < ApplicationController
  def new
    @plant = Plant.find(params[:plant_id])
    @plant_tag = PlantTag.new
  end

  def create
    @tags = Tag.where(id: params[:plant_tag][:tag])
    @plant = Plant.find(params[:plant_id])
    @tags.each do |tag|
      @plant_tag = PlantTag.new(tag: tag, plant: @plant)
      @plant_tag.save
    end
    redirect_to garden_path(@plant.garden)
  end

  private

  def plant_tag_params
    params.require(:plant_tag).permit(:plant, :tag)
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def create
    @plant = Plant.new(plant_params)
    @garden = Garden.find(params[:garden_id])
    @plant.garden = @garden
    if @plant.save
      redirect_to garden_path(@garden)
    else
      render :new
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy
    redirect_to garden_path(@plant.garden)
  end

  private

  def plant_params
    # WHITELISTING
    params.require(:plant).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plant_tags_helper.rb
module PlantTagsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/_form.html.erb
<%= simple_form_for(@garden) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :banner_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/gardens/edit.html.erb
<h1>Editing Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Show', @garden %> |
<%= link_to 'Back', gardens_path %>

app/views/gardens/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Gardens</h1>

<div class="container mt-5">
  <% @gardens.each do |garden| %>
    <div class="row justify-content-center mb-3">
      <div class="col-6 rounded text-center py-3" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= garden.banner_url %>)">
        <h2 class="text-white"><%= garden.name %></h2>
        <div class="links">
          <p><%= link_to 'Show', garden %></p>
          <p><%= link_to 'Edit', edit_garden_path(garden) %></p>
          <p><%= link_to 'Destroy', garden, method: :delete, data: { confirm: 'Are you sure?' } %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>

<%= link_to 'New Garden', new_garden_path %>

app/views/gardens/new.html.erb
<h1>New Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Back', gardens_path %>

app/views/gardens/show.html.erb
<p id="notice"><%= notice %></p>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @garden.banner_url %>);">
  <div class="container">
    <h1 class="text-center"><%= @garden.name  %></h1>
  </div>
</div>

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-4">
      <h4>Add a plant</h4>
      <%= simple_form_for [@garden, @plant] do |f| %>
        <%= f.input :name, placeholder: "Beautiful plant" %>
        <%= f.input :image_url, placeholder: "Something nice from Google" %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>



<% @garden.plants.each do |plant| %>
  <div class="card-category mt-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= plant.image_url %>)">
    <%= plant.name %>
  <%= link_to "+", plant_path(plant), method: :delete, data: { confirm: "Do you really wanna hurt me?" }, class: "card-remove-link" %>
    <div class="card-tags">
      <% plant.tags.each do |tag| %>
        <span><%= tag.name %></span>
      <% end %>
      <%= link_to "+", new_plant_plant_tag_path(plant) %>
    </div>
  </div>
<% end %>


<%= link_to 'Edit', edit_garden_path(@garden) %> |
<%= link_to 'Back', gardens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardenPlants</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/plant_tags/new.html.erb
<h1>Create a tag for <%= @plant.name %></h1>

<%= simple_form_for [@plant, @plant_tag] do |f| %>
  <%= f.input :tag, collection: Tag.all, include_blank: false, input_html: {multiple: true, data: {controller: 'select2', select2_options_value: {tags: true}}} %>
  <%= f.submit %>
<% end %>